apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: h6akrun5p-go
  janus-idp.io/tekton: h6akrun5p-go
  backstage.io/kubernetes-id: h6akrun5p-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: h6akrun5p-go
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
